#liulinsheng@wind-mobi.com 20180809 begin
# In case the platform does NOT support this type of sensors
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y   += gpio_set.o 

#liulinsheng@wind-mobi.com 20180809 end